[CmdletBinding()]
param(
    [Parameter()]
    [string] $IconDirectory = (Join-Path $PSScriptRoot '..\workbench\icons\octicons')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'WorkbenchIconPreview.ps1')

$commit = '6220ff87f3ddd923b05ffdac7e2d9cb714213205'
$iconNames = @(
    'check-16',
    'chevron-down-12',
    'chevron-down-16',
    'chevron-left-16',
    'chevron-right-12',
    'chevron-right-16',
    'chevron-up-16',
    'checkbox-16',
    'checkbox-fill-16',
    'code-16',
    'code-review-16',
    'comment-16',
    'comment-ai-16',
    'copilot-16',
    'copy-16',
    'diff-16',
    'diff-added-16',
    'diff-modified-16',
    'diff-removed-16',
    'diff-renamed-16',
    'eye-16',
    'eye-closed-16',
    'file-directory-fill-16',
    'file-directory-open-fill-16',
    'file-16',
    'file-added-16',
    'file-code-16',
    'file-diff-16',
    'file-removed-16',
    'fold-16',
    'fold-down-16',
    'fold-up-16',
    'filter-16',
    'kebab-horizontal-16',
    'people-16',
    'plus-16',
    'shield-16',
    'shield-check-16',
    'shield-lock-16',
    'sparkle-16',
    'sparkle-fill-16',
    'square-16',
    'unfold-16',
    'x-16'
)

if (-not (Test-Path -LiteralPath $IconDirectory -PathType Container)) {
    throw "The vendored Octicon directory '$IconDirectory' does not exist."
}
if (-not (Test-Path -LiteralPath (Join-Path $IconDirectory 'LICENSE.txt') -PathType Leaf)) {
    throw "The vendored Octicon license is missing from '$IconDirectory'."
}

$symbols = foreach ($iconName in $iconNames) {
    $sourcePath = Join-Path $IconDirectory "$iconName.svg"
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "The vendored Octicon '$iconName' is missing from '$IconDirectory'."
    }
    $svg = (Get-Content -LiteralPath $sourcePath -Raw).Trim()
    $match = [regex]::Match($svg, '^<svg[^>]*viewBox="(?<viewBox>[^"]+)"[^>]*>(?<content>[\s\S]*)</svg>$')
    if (-not $match.Success -or $match.Groups['viewBox'].Value -notin @('0 0 12 12', '0 0 16 16')) {
        throw "Octicon '$iconName' does not use a supported SVG viewBox."
    }
    $viewBox = $match.Groups['viewBox'].Value
    $content = $match.Groups['content'].Value.Trim()
    if (-not $content) {
        throw "Octicon '$iconName' is empty."
    }
    "  <symbol id=`"octicon-$iconName`" viewBox=`"$viewBox`">$content</symbol>"
}

$sprite = @(
    '<svg xmlns="http://www.w3.org/2000/svg">'
    '<!-- Generated by hosted_copilot/tools/New-WorkbenchOcticonSprite.ps1. -->'
    '<!-- Source: https://github.com/primer/octicons/tree/6220ff87f3ddd923b05ffdac7e2d9cb714213205/icons -->'
    $symbols
    '</svg>'
) -join "`n"
$spritePath = Join-Path $IconDirectory 'sprite.svg'
Set-Content -LiteralPath $spritePath -Value $sprite -Encoding utf8NoBOM
$previewPngPath = New-WorkbenchIconPreview -IconDirectory $IconDirectory -FamilyName 'GitHub Primer Octicons' -Commit $commit -SymbolPrefix 'octicon' -IconNames $iconNames

[pscustomobject]@{
    Status = 'generated'
    Commit = $commit
    IconCount = $iconNames.Count
    SpritePath = $spritePath
    PreviewPngPath = $previewPngPath
    LicensePath = (Join-Path $IconDirectory 'LICENSE.txt')
}
