[CmdletBinding()]
param(
    [Parameter()]
    [string] $IconDirectory = (Join-Path $PSScriptRoot '..\workbench\icons')
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$commit = '1c47ab36a4bb845c437866405c2fa67b8ca0fe36'
$iconNames = @(
    'arrow-left',
    'check',
    'check-compact',
    'checklist',
    'checklist-compact',
    'chevron-down',
    'chevron-down-compact',
    'chevron-right-compact',
    'chevron-up',
    'circle-slash',
    'circle-slash-compact',
    'cloud-upload',
    'collection',
    'collection-small',
    'copy',
    'debug-disconnect',
    'debug-disconnect-compact',
    'diff',
    'discard',
    'download',
    'edit',
    'ellipsis',
    'folder',
    'git-branch-compact',
    'git-commit',
    'git-pull-request-draft',
    'graph',
    'inbox',
    'json',
    'library',
    'link',
    'list-selection',
    'lock',
    'new-session',
    'open-preview',
    'pass',
    'repo-forked',
    'save',
    'search',
    'shield',
    'shield-compact',
    'sign-out',
    'tasklist',
    'warning'
)

if (-not (Test-Path -LiteralPath $IconDirectory -PathType Container)) {
    throw "The vendored Codicon directory '$IconDirectory' does not exist."
}
if (-not (Test-Path -LiteralPath (Join-Path $IconDirectory 'LICENSE.txt') -PathType Leaf)) {
    throw "The vendored Codicon license is missing from '$IconDirectory'."
}

$symbols = foreach ($iconName in $iconNames) {
    $sourcePath = Join-Path $IconDirectory "$iconName.svg"
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "The vendored Codicon '$iconName' is missing from '$IconDirectory'."
    }
    $svg = (Get-Content -LiteralPath $sourcePath -Raw).Trim()
    $match = [regex]::Match($svg, '^<svg[^>]*viewBox="(?<viewBox>[^"]+)"[^>]*>(?<content>[\s\S]*)</svg>$')
    if (-not $match.Success -or $match.Groups['viewBox'].Value -notin @('0 0 10 10', '0 0 12 12', '0 0 16 16')) {
        throw "Codicon '$iconName' does not use a supported SVG viewBox."
    }
    $viewBox = $match.Groups['viewBox'].Value
    $content = $match.Groups['content'].Value.Trim()
    if (-not $content) {
        throw "Codicon '$iconName' is empty."
    }
    "  <symbol id=`"codicon-$iconName`" viewBox=`"$viewBox`">$content</symbol>"
}

$sprite = @(
    '<svg xmlns="http://www.w3.org/2000/svg">'
    '<!-- Generated by hosted_copilot/tools/New-WorkbenchCodiconSprite.ps1. -->'
    '<!-- Source: https://github.com/microsoft/vscode-codicons/tree/1c47ab36a4bb845c437866405c2fa67b8ca0fe36/src/icons -->'
    $symbols
    '</svg>'
) -join "`n"
$spritePath = Join-Path $IconDirectory 'codicons.svg'
Set-Content -LiteralPath $spritePath -Value $sprite -Encoding utf8NoBOM

[pscustomobject]@{
    Status = 'generated'
    Commit = $commit
    IconCount = $iconNames.Count
    SpritePath = $spritePath
    LicensePath = (Join-Path $IconDirectory 'LICENSE.txt')
}
