blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/WodansSon/terraform-azurerm-ai-assisted-development/discussions
    about: Ask questions and discuss ideas with the community
